export const types = {
  START_FETCH_NEWS: 'START_FETCH_NEWS',
  STOP_FETCH_NEWS: 'STOP_FETCH_NEWS',
  CATCH_ERROR: 'CATCH_ERORR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  GET_NEWS_ARTICLES: 'GET_NEWS_ARTICLES',
};
