export const types = {
  INIT: 'INIT',
  START_FETCH_NEWS: 'START_FETCH_NEWS',
  STOP_FETCH_NEWS: 'STOP_FETCH_NEWS',
  CATCH_ERROR: 'CATCH_ERORR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  GET_NEWS_ARTICLES: 'GET_NEWS_ARTICLES',
  CHAGNE_CATEGORY: 'CHANGE_CATEGORY',
  START_SEARCH_QUERY: 'START_SEARCH_QUERY',
  GET_SEARCH_QUERY: 'GET_SEARCH_QUERY',
  CLEAR_SEARCH_QUERY: 'CLEAR_SEARCH_QUERY',

  // INFINITE SCROLL WORKIN IN PROCESS...
  GET_MORE_NEWS: 'GET_MORE_NEWS',
  CHANGE_PAGE_SIZE: 'CHANGE_PAGE_SIZE',
  START_FETCH_MORE_NEWS: 'START_FETCH_MORE_NEWS',
  STOP_FETCH_MORE_NEWS: 'STOP_FETCH_MORE_NEWS',
  SET_DEFAULT_PAGE_SIZE: 'SET_DEFAULT_PAGE_SIZE',
};
