export const types = {
  INIT: 'INIT',
  START_FETCH_NEWS: 'START_FETCH_NEWS',
  STOP_FETCH_NEWS: 'STOP_FETCH_NEWS',
  CATCH_ERROR: 'CATCH_ERORR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  GET_NEWS_ARTICLES: 'GET_NEWS_ARTICLES',
  CHAGNE_CATEGORY: 'CHANGE_CATEGORY',
  START_SEARCH_QUERY: 'START_SEARCH_QUERY',
  GET_SEARCH_QUERY: 'GET_SEARCH_QUERY',
  CLEAR_SEARCH_QUERY: 'CLEAR_SEARCH_QUERY',
};
